-- ============================================================
-- Quran Analytics Database Schema
-- SQLite 3.x compatible
-- 
-- Tables:
--   surahs          → chapter metadata
--   verses          → all 6236 verses (Arabic + English)
--   root_words      → known Arabic roots and their semantic domains
--   verse_roots     → many-to-many: which roots appear in which verse
--   themes          → semantic theme clusters (generated by ML pipeline)
--   verse_themes    → many-to-many: verse → theme assignments
--   embeddings_meta → tracks embedding generation runs
-- ============================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- ── Surahs ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS surahs (
    surah_number       INTEGER PRIMARY KEY,        -- 1-114
    name_arabic        TEXT    NOT NULL,
    name_english       TEXT    NOT NULL,
    revelation_type    TEXT    NOT NULL CHECK(revelation_type IN ('Meccan', 'Medinan')),
    revelation_order   INTEGER NOT NULL,           -- 1-114, chronological order
    total_verses       INTEGER NOT NULL,
    juz_start          INTEGER,                    -- which Juz this surah starts in (1-30)
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── Verses ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS verses (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id        TEXT    NOT NULL UNIQUE,  -- e.g. "2:255" (surah:verse)
    surah_number    INTEGER NOT NULL REFERENCES surahs(surah_number),
    verse_number    INTEGER NOT NULL,
    arabic_text     TEXT    NOT NULL,
    english_text    TEXT,                     -- Sahih International translation
    word_count_ar   INTEGER,                  -- Arabic word count
    char_count_ar   INTEGER,                  -- Arabic character count
    has_embedding   INTEGER DEFAULT 0,        -- 1 if embedding generated
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(surah_number, verse_number)
);

-- ── Root Words ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS root_words (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    root_arabic     TEXT    NOT NULL UNIQUE,  -- e.g. "عدل"
    root_english    TEXT    NOT NULL,         -- e.g. "justice/fairness"
    domain          TEXT    NOT NULL,         -- e.g. "Ethics & Law"
    total_occurrences INTEGER DEFAULT 0,      -- updated by trigger/script
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── Verse-Root Associations ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS verse_roots (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id        TEXT    NOT NULL REFERENCES verses(verse_id),
    root_arabic     TEXT    NOT NULL REFERENCES root_words(root_arabic),
    surah_number    INTEGER NOT NULL,         -- denormalized for faster filtering
    revelation_type TEXT    NOT NULL,         -- denormalized: 'Meccan' or 'Medinan'
    revelation_order INTEGER NOT NULL,        -- denormalized for chronological queries

    UNIQUE(verse_id, root_arabic)
);

-- ── Themes ───────────────────────────────────────────────────────────────────
-- These are generated by the KMeans clustering pipeline (embeddings/cluster_themes.py)
-- Labels are assigned semi-manually after reviewing cluster centroids
CREATE TABLE IF NOT EXISTS themes (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    cluster_id      INTEGER NOT NULL UNIQUE,  -- from KMeans
    label_english   TEXT    NOT NULL,         -- e.g. "Divine Mercy & Forgiveness"
    label_arabic    TEXT,                     -- optional Arabic label
    description     TEXT,
    color_hex       TEXT DEFAULT '#4A90D9',   -- for visualization
    verse_count     INTEGER DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── Verse-Theme Assignments ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS verse_themes (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    verse_id        TEXT    NOT NULL REFERENCES verses(verse_id),
    cluster_id      INTEGER NOT NULL REFERENCES themes(cluster_id),
    confidence      REAL    DEFAULT 1.0,      -- distance-to-centroid normalized
    surah_number    INTEGER NOT NULL,         -- denormalized for fast filtering
    revelation_type TEXT    NOT NULL,

    UNIQUE(verse_id, cluster_id)
);

-- ── Embedding Metadata ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS embeddings_meta (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    model_name      TEXT    NOT NULL,         -- e.g. "bert-base-multilingual-cased"
    embedding_dim   INTEGER NOT NULL,         -- e.g. 768
    total_verses    INTEGER NOT NULL,
    npy_path        TEXT    NOT NULL,         -- path to saved .npy file
    run_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes           TEXT
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- These make the dashboard queries fast enough to feel instant

CREATE INDEX IF NOT EXISTS idx_verses_surah        ON verses(surah_number);
CREATE INDEX IF NOT EXISTS idx_verses_has_embedding ON verses(has_embedding);

CREATE INDEX IF NOT EXISTS idx_verse_roots_root     ON verse_roots(root_arabic);
CREATE INDEX IF NOT EXISTS idx_verse_roots_surah    ON verse_roots(surah_number);
CREATE INDEX IF NOT EXISTS idx_verse_roots_rev_type ON verse_roots(revelation_type);
CREATE INDEX IF NOT EXISTS idx_verse_roots_rev_order ON verse_roots(revelation_order);

CREATE INDEX IF NOT EXISTS idx_verse_themes_cluster ON verse_themes(cluster_id);
CREATE INDEX IF NOT EXISTS idx_verse_themes_surah   ON verse_themes(surah_number);
CREATE INDEX IF NOT EXISTS idx_verse_themes_rev     ON verse_themes(revelation_type);

CREATE INDEX IF NOT EXISTS idx_surahs_rev_order     ON surahs(revelation_order);
CREATE INDEX IF NOT EXISTS idx_surahs_rev_type      ON surahs(revelation_type);

-- ── Views ─────────────────────────────────────────────────────────────────────
-- Pre-joined views used by the dashboard

-- Full verse details (most common query)
CREATE VIEW IF NOT EXISTS v_verses_full AS
SELECT
    v.verse_id,
    v.surah_number,
    v.verse_number,
    v.arabic_text,
    v.english_text,
    v.word_count_ar,
    s.name_arabic,
    s.name_english,
    s.revelation_type,
    s.revelation_order,
    s.juz_start
FROM verses v
JOIN surahs s ON v.surah_number = s.surah_number;

-- Root word distribution with surah context
CREATE VIEW IF NOT EXISTS v_root_distribution AS
SELECT
    vr.root_arabic,
    rw.root_english,
    rw.domain,
    vr.surah_number,
    s.name_english       AS surah_name_en,
    s.revelation_type,
    s.revelation_order,
    COUNT(*)             AS occurrences
FROM verse_roots vr
JOIN root_words rw ON vr.root_arabic = rw.root_arabic
JOIN surahs s      ON vr.surah_number = s.surah_number
GROUP BY vr.root_arabic, vr.surah_number;

-- Theme distribution by revelation period
CREATE VIEW IF NOT EXISTS v_theme_by_revelation AS
SELECT
    t.label_english,
    t.label_arabic,
    t.color_hex,
    vt.revelation_type,
    COUNT(*) AS verse_count
FROM verse_themes vt
JOIN themes t ON vt.cluster_id = t.cluster_id
GROUP BY t.label_english, vt.revelation_type;

-- ── Sample Queries (for reference / testing) ─────────────────────────────────

-- Q: How many times does root "عدل" appear, and in which surahs?
-- SELECT root_arabic, surah_number, occurrences
-- FROM v_root_distribution
-- WHERE root_arabic = 'عدل'
-- ORDER BY occurrences DESC;

-- Q: Which themes dominate Meccan surahs vs Medinan?
-- SELECT label_english, revelation_type, verse_count
-- FROM v_theme_by_revelation
-- ORDER BY revelation_type, verse_count DESC;

-- Q: All verses in surah 2 with their themes
-- SELECT v.verse_id, v.arabic_text, v.english_text, t.label_english
-- FROM v_verses_full v
-- LEFT JOIN verse_themes vt ON v.verse_id = vt.verse_id
-- LEFT JOIN themes t ON vt.cluster_id = t.cluster_id
-- WHERE v.surah_number = 2
-- ORDER BY v.verse_number;
